name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      working-directory: terraform
      run: terraform plan

    - name: Terraform Apply
      working-directory: terraform
      run: terraform apply -auto-approve

    # Optional: Output something like EC2 IP
    - name: Get EC2 IP
      id: get_ip
      run: |
        IP=$(terraform output -raw public_ip)
        echo "EC2 IP: $IP"
        echo "ip=$IP" >> "$GITHUB_OUTPUT"

